from enum import Enum


class TimeUnit(Enum):
    SECOND = 1
    MILLISECOND = 2


TIME_UNIT = TimeUnit.SECOND

USER_SPEED_MPS = 1.4
SIM_STEP_SECONDS = 1

ENABLE_ANIMATION = False
ANIMATION_STEP_STRIDE = 5
ANIMATION_MAX_FRAMES = 300
ANIMATION_FORMAT = "gif"  # "mp4" or "gif"

PRINT_NEAREST_DISTANCES = False
NEAREST_NODES_TO_PRINT = 3

RSSI_REFERENCE_DISTANCE_M = 1.0
RSSI_AT_REFERENCE_DBM = -20.0
RSSI_ENVIRONMENT_COEFF = 2.7
WIFI_RETRANSMISSION_RTT_S = 0.03  # 30ms

# WiFi throughput model (YAFS BW units are MB/s).
WIFI_MAX_BW_MBPS = 54.0 / 8.0
WIFI_MEDIUM_BW_MBPS = 11.0 / 8.0
WIFI_MIN_BW_MBPS = 1.0 / 8.0

# Galaxy S4 WiFi tail model.
WIFI_TAIL_TIME_S = 0.210
WIFI_TAIL_POWER_W = 0.289

# Sensor WiFi model.
SENSOR_WIFI_TAIL_TIME_S = 0.18
SENSOR_WIFI_TAIL_POWER_W = 0.1212
SENSOR_WIFI_PROMOTION_TIME_S = 0.30
SENSOR_WIFI_PROMOTION_POWER_W = 0.2425

# Sensor BLE model (sensor <-> edge, near distance ~0.5m).
SENSOR_BLE_TAIL_TIME_S = 4.77
SENSOR_BLE_TAIL_POWER_W = 0.0341
SENSOR_BLE_TX_POWER_W = 0.1115
SENSOR_BLE_RX_POWER_W = 0.1172
SENSOR_BLE_DATA_BW_MBPS = 0.305

# Task1 profile (ECG classification)
TASK1_ID = "Task1"
TASK1_PERIOD_S = 10
TASK1_COMPLEXITY_MI = 500
TASK1_DATA_SIZE_KB = 36
TASK1_MAX_RESPONSE_TIME_S = 15
TASK1_CLASSIFICATION = "critical analysis"
TASK_EXECUTION_MODE = "EDGE"  # EDGE | FOG

OPTIMIZATION_METHOD = "LP"
ALPHA_LATENCY = 0.0
BETA_ENERGY = 1.0
OFFLOADING_DECISION_PERIOD_S = 1
TASK1_MIGRATION_STATE_SIZE_KB = 20.0

# Task2 profile (SmartWatch audio analysis)
TASK2_ID = "Task2"
TASK2_PERIOD_S = 10
TASK2_COMPLEXITY_MI = 1000
TASK2_DATA_SIZE_KB = 500
TASK2_TASK_SIZE_KB = 256
TASK2_RESULT_SIZE_KB = 4
TASK2_MAX_RESPONSE_TIME_S = None  # unlimited
TASK2_CLASSIFICATION = "data analysis"
TASK2_TRANSPORT = "UDP"

# Task3 profile (SmartWatch temperature/context management)
TASK3_ID = "Task3"
TASK3_PERIOD_S = 60
TASK3_COMPLEXITY_MI = 10
TASK3_DATA_SIZE_KB = 10
TASK3_TASK_SIZE_KB = 50
TASK3_RESULT_SIZE_B = 707
TASK3_MAX_RESPONSE_TIME_S = 0.5
TASK3_CLASSIFICATION = "context management"
TASK3_TRANSPORT = "TCP"

# Task4 profile (SmartWatch humidity/context management)
TASK4_ID = "Task4"
TASK4_PERIOD_S = 60
TASK4_COMPLEXITY_MI = 10
TASK4_DATA_SIZE_KB = 10
TASK4_TASK_SIZE_KB = 50
TASK4_RESULT_SIZE_B = 707
TASK4_MAX_RESPONSE_TIME_S = 0.5
TASK4_CLASSIFICATION = "context management"
TASK4_TRANSPORT = "TCP"

# Task5 profile (ECG compression/context management)
TASK5_ID = "Task5"
TASK5_PERIOD_S = 10
TASK5_COMPLEXITY_MI = 211
TASK5_DATA_SIZE_KB = 240
TASK5_TASK_SIZE_KB = 250
TASK5_RESULT_SIZE_KB = 16.8
TASK5_MAX_RESPONSE_TIME_S = 0.5
TASK5_CLASSIFICATION = "context management"
TASK5_TRANSPORT = "TCP"

# Static scenario link model (fixed RSSI for monitor-driven link updates).
STATIC_LINK_RSSI_DBM = -85.0
